INSERT INTO watches (name, description, price, image_url) VALUES
('Emerald Classic', 'Elegant watch with genuine leather strap and minimalist dial.', 6602, './assets/watch1.jpg'),
('Royal Skeleton', 'Skeleton dial with automatic movement, perfect for collectors.', 177172, './assets/watch2.jpg'),
('Vintage Roman', 'Roman numeral dial exudes vintage charm and class.', 18062, './assets/watch3.jpg'),
('Fossil Bold', 'Rugged Fossil design with bold contrast accents.', 184252, './assets/watch4.jpg'),
('Blush Crystal', 'Crystal-studded dial adds luxury and femininity.', 84915, './assets/watch5.jpg'),
('Sapphire Steel', 'Bright blue chronograph with stainless steel build.', 135188, './assets/watch6.jpg'),
('Carbon Retro', 'Retro-styled dial with matte finish for daily wear.', 69953, './assets/watch7.jpg'),
('Steel Elegance', 'Polished silver elegance for formal occasions.', 112249, './assets/watch8.jpg'),
('Midnight Gold', 'Classic midnight black with golden accents.', 46431, './assets/watch9.jpg'),
('Rose Chrono', 'Chronograph with rose gold casing and tachymeter.', 124429, './assets/watch10.jpg'),
('Ivory Dial', 'Ivory dial with sunburst effect and mesh strap.', 57361, './assets/watch11.jpg'),
('Navy Luxe', 'Luxury blue dial with navy leather band.', 79810, './assets/watch12.jpg'),
('Matte Black', 'Matte black stealth design for urban style.', 158436, './assets/watch13.jpg'),
('Rose Minimal', 'Minimal dial with rose finish, a sleek statement.', 104959, './assets/watch14.jpg'),
('Gold Precision', 'Gold-plated case with precise date display.', 200110, './assets/watch15.jpg'),
('Ebony Edge', 'Ebony finish with sporty red details.', 34057, './assets/watch16.jpg'),
('Carbon Chrono', 'Multi-function chronograph with black accents.', 125551, './assets/watch17.jpg'),
('Diamond Dual', 'Dual-tone with embedded diamond markers.', 174351, './assets/watch18.jpg'),
('Aurora Shine', 'Iridescent dial with galaxy-inspired finish.', 8055, './assets/watch19.jpg'),
('Titan Heritage', 'Heritage design with a classic dual dial.', 31955, './assets/watch20.jpg'),
('Rosé Delight', 'Delicate rose case with crystal-encrusted bezel.', 74958, './assets/watch21.jpg'),
('White Luxe', 'White ceramic body with gold-tone hour markers.', 235841, './assets/watch22.jpg'),
('Diver’s Edge', 'Diver-inspired rugged case and rotating bezel.', 27673, './assets/watch23.jpg'),
('Metro Chrono', 'Slim and sleek with city-style numerals.', 14261, './assets/watch24.jpg'),
('Executive Elite', 'Executive black dial with elegant leather strap.', 49333, './assets/watch25.jpg'),
('Stellar Shine', 'Shining silver dial with elevated design cues.', 164253, './assets/watch26.jpg'),
('Shadow Strike', 'Black-on-black style for bold personalities.', 123528, './assets/watch27.jpg'),
('Silver Square', 'Elegant square dial in steel with link bracelet.', 131548, './assets/watch28.jpg'),
('Gold Rush', 'Sporty golden frame with textured crown.', 19600, './assets/watch29.jpg'),
('Urban Sport', 'Oversized dial perfect for adventure seekers.', 87138, './assets/watch30.jpg'),
('Race Chrono', 'Racing dial with red accent markers.', 213015, './assets/watch31.jpg'),
('Royal Violet', 'Royal purple sunburst dial for statement makers.', 178153, './assets/watch32.jpg'),
('Titanium Pro', 'Titanium body with lightweight feel.', 75479, './assets/watch33.jpg'),
('Golden Glint', 'Gold mesh strap with intricate detailing.', 39647, './assets/watch34.jpg'),
('Titan Edge', 'Edge series with ultra-thin body and dark dial.', 9387, './assets/watch35.jpg'),
('Silver Storm', 'Silver and black finish with dual subdials.', 216279, './assets/watch36.jpg'),
('Elegant Mesh', 'Mesh design with clean analog dial.', 23869, './assets/watch37.jpg'),
('Dual Tone Luxe', 'Two-tone luxury with bold date window.', 121716, './assets/watch38.jpg'),
('Ocean Blue', 'Ocean-inspired deep blue chronograph.', 217408, './assets/watch39.jpg'),
('Trio Combo', 'Three-watch combo for couple and kids.', 26052, './assets/watch40.jpg'),
('White Royale', 'Premium ceramic finish with Roman numerals.', 55242, './assets/watch41.jpg'),
('Jet Black Dive', 'Jet-black diving dial with luminous hands.', 70078, './assets/watch42.jpg'),
('Gold Master', 'Oversized chronograph with gold tones.', 50113, './assets/watch43.jpg'),
('Platinum Pearl', 'Pearl dial with polished two-tone band.', 247931, './assets/watch44.jpg'),
('Ivory Glimmer', 'Glimmering ivory finish with delicate texture.', 137766, './assets/watch45.jpg'),
('Chrono Titan', 'Chrono function with steel casing and red hands.', 153960, './assets/watch46.jpg'),
('Nightfall', 'Dark themed watch with amber tint.', 167221, './assets/watch47.jpg'),
('Crimson Beauty', 'Glossy golden case with mother-of-pearl dial.', 112357, './assets/watch48.jpg');